version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: quiz-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: quiz-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - quiz-network

  backend:
    build: ./backend
    container_name: quiz-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/quiz-app?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - quiz-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: quiz-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - quiz-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  quiz-network:
    driver: bridge
